repos:
-   repo: https://github.com/golangci/golangci-lint
    rev: v1.61.0
    hooks:
    -   id: golangci-lint-full
-   repo: .
    rev: v0.12.0
    hooks:
    -   id: golines
        exclude: internal/testdata
-   repo: https://gitlab.com/matthewhughes/go-pre-commit
    rev: v0.3.0
    hooks:
    -   id: go-mod-tidy
-   repo: https://gitlab.com/matthewhughes/common-changelog
    rev: v0.2.0
    hooks:
    -   id: validate-changelog
